logs:
  enabled: true

finders:
  aws:
    costs:
      gp2Volumes: true
      detachedVolumes: true
      volumesOnStoppedInstances: true
      detachedIps: true
      oldSnapshots:
        enabled: true
        daysOfRetention: 30

    security:
      insecureSecurityGroups: true
      rdsInstancePubliclyAccessible: true
      s3BucketNoPublicAccessBlock: true
